user/mysite/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from saki import views

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^saki/', include('saki.urls', namespace="saki")),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^user/$', views.UserView.as_view(), name='user'),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root' : settings.MEDIA_ROOT}),
                        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root' : settings.STATIC_ROOT}),
                       )

user/saki/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from saki import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^user/$', views.UserView.as_view(), name='user'),
                       )

user/saki/models.py
import datetime
from django.db import models
from django.utils import timezone
from datetime import datetime
from time import time


def get_upload_file_name(instance, filename):
    return "uploaded_files/%s" % (filename)

class User(models.Model):
    class Meta:
        verbose_name_plural = "Users"
    
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20, default='None')
    email = models.EmailField(max_length=30, default='None')
    thumbnail = models.FileField(upload_to=get_upload_file_name, default = 'None')

    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.first_name
        return self.last_name
        return self.email
        return self.thumbnail
        
    def admin_image(self):
        return '<img src="%s"/>' % self.thumbnail
    admin_image.allow_tags = True


    

user/saki/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import generic

from saki.models import User


class IndexView(generic.ListView):
    template_name = 'saki/index.html'
    context_object_name = 'object_list'
    
    def get_queryset(self):
               return User.objects.filter(
                                       pub_date__lte=timezone.now()
                                       ).order_by('-pub_date')[:20]


class UserView(generic.ListView):
    template_name = 'saki/user.html'
    context_object_name = 'object_list'
    
    def get_queryset(self):
        return User.objects.filter(
                                    pub_date__lte=timezone.now()
                                    ).order_by('-pub_date')[:20]

user/saki/templates/saki/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <meta name='discription' content="Django Sample Page"> 
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'saki/saki.css' %}" /> 
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    </script>
    <script>
    //     $(document).ready(function(){
    //         $(".img").click( function() {
    //           $(this).fadeOut('normal');
    // 　　　　　});



        });
    </script>
    <title>Saki</title>
</head>

<body>
    <div id='header'>
        <div class='menu'>
            <ul>
                <li><a href='#'>Home</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>About</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>Press</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>Career</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>Links</a><span style="margin-right: 1em;"></span></li>
            </ul>
        </div>
        <div id='title-1'>
            {% load staticfiles %}
            <img src="{% static 'saki/nmr_2.png' %}" class="img" width='100px' height='70px'>
            <h1>User</h1>
        </div>
        <div id='title-2'>
            <h2>Sample app</h2></div>
    </div>
    </div>

    <div id='navi'>
        <h2>Menu</h2>
        <a class="btn" href="{% url 'saki:user'%}">Users</a>

    </div>

        <div id='contents'>
        <p>This is my sample page. Users can create, edit, update, and destroy (delete) users.
        Users first name, last name, and email address fields. First name is required. 
        Email should be a valid email.</p>
    </div>
</body>

user/saki/templates/saki/user.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <meta name='discription' content="Users"> 
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'saki/saki.css' %}" /> 
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    </script>
    <script>
    //     $(document).ready(function(){
    //         $(".img").click( function() {
    //           $(this).fadeOut('normal');
    // 　　　　　});



        });
    </script>
    <title>User</title>
</head>

<body>
    <div id='header'>
        <div class='menu'>
            <ul>
                <li><a href="{% url 'saki:index'%}">Home</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>About</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>Press</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>Career</a><span style="margin-right: 1em;"></span></li>
                <li><a href='#'>Links</a><span style="margin-right: 1em;"></span></li>
            </ul>
        </div>
        <div id='title-1'>
            {% load staticfiles %}
            <img src="{% static 'saki/nmr_2.png' %}" class="img" width='100px' height='70px'>
            <h1><a href="{% url 'saki:index'%}">Users</a></h1>
        </div>
        <div id='title-2'>
            <h2>Sample App</h2></div>
    </div>
    </div>

    <div id='contents'>
        <div id='article'>
        {% block content %}<br>
            <ul>
            {% for user in object_list %}
                <ul><h3>{{ user.first_name}} {{ user.last_name}}</h3>
                    <li><img src = "{{user.thumbnail.url}}", width = "200"/></li>
                    <li>{{ user.email|linebreaks }}</li>
                    <br>
                </ul>
            {% endfor %}
            </ul>
         {% endblock %}
        <div>
    </div>
</body>